[package]
name = "ggl-wasm-example"

[build]
target = "index.html"
release = false
dist = "dist"
public_url = "/"

[watch]
watch = ["src", "../../src"]
ignore = ["dist"]

[serve]
address = "127.0.0.1"
port = 8080
open = false
no_autoreload = false

[clean]
dist = "dist"
cargo = false
