name: "Continuous Integration"
on:
  push:
    branches-ignore: ["main"]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        # - ubuntu-24.04
        # - ubuntu-22.04
        # - ubuntu-22.04-arm
        # - ubuntu-24.04-arm
        - macos-latest
        # - macos-14
        # - macos-15
        # - macos-13
        # - windows-latest
        # - windows-2025
        # - windows-2022
        # - windows-11-arm
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Install omnix
        run: nix --accept-flake-config profile install "github:juspay/omnix"
      - run: om ci
      - run: nix develop -c "just build-wasm"
